package com.example.StreamPractice.solution1;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class PracticeQuestions {
    record Student(int age, String name) {}
    public static void main(String[] args) {
        List<Product> mockProducts = MockDataUtil.getMockProducts();
        List<Order> mockOrders = MockDataUtil.getMockOrders();

        // 1. Get all orders placed via Mobile
        List<Order> mobileApp = mockOrders.stream().filter(order -> order.getSource().equals("MOBILE_APP")).toList();
        System.out.println("1. Get all orders placed via Mobile --> "+ mobileApp.size());
        System.out.println("");

        // 2. List all the product names
        List<String> productNameList = mockProducts.stream().map(Product::getProductName).toList();
        System.out.println("2. List all the product names --> "+productNameList);
        System.out.println("");

        // 3. Count the number of orders placed for each product.
        Map<String, Long> OrdersForEachProduct = mockOrders.stream().collect(Collectors.groupingBy(Order::getProductId, Collectors.counting()));
        System.out.println("3. Count the number of orders placed for each product --> " + OrdersForEachProduct);
        System.out.println("");

        // 4. Find the total revenue generated by "Gaming Keyboard" orders.
        Product gamingKeyboard = mockProducts.stream().filter(product -> product.getProductName().equals("Gaming Keyboard")).findFirst().get();
        Double gamingKeyBoardRevenue = mockOrders.stream().filter(order -> order.getProductId().equals(gamingKeyboard.getProductId()))
                .mapToDouble(Order::getOrderAmount).sum();
        System.out.println("4. Find the total revenue generated by Gaming Keyboard orders -> "+gamingKeyBoardRevenue);
        System.out.println("");

        //5. Get a distinct list of payment methods used in the orders.
        List<String> distinctPaymentMode = mockOrders.stream().map(Order::getPaymentMode).distinct().toList();
        System.out.println("5. Get a distinct list of payment methods used in the orders -> "+distinctPaymentMode);
        System.out.println("");

        //6. Get the top 2 products with the highest price.
        List<Product> sortedList = mockProducts.stream().sorted(Comparator.comparingDouble(Product::getPrice).reversed()).limit(2).toList();
        System.out.println("6. Get the top 2 products with the highest price --> "+sortedList);
        System.out.println("");

        //7️. Detect duplicate orders (same orderId) and list them.
        List<String> duplicateOrders = mockOrders.stream().collect(Collectors.groupingBy(Order::getOrderId))
                .entrySet()
                .stream()
                .filter(entry -> entry.getValue().size() > 1)
                .map(Map.Entry::getKey)
                .toList();
        System.out.println("7. Detect duplicate orders (same orderId) and list them -> "+duplicateOrders);
        System.out.println("");

        // 8.For each product, find total quantity sold across all orders.
        Map<String, Integer> totalProductsQuantity = mockOrders.stream()
                .collect(Collectors.groupingBy(Order::getProductId, Collectors.summingInt(Order::getQuantity)));
        System.out.println("8.For each product, find total quantity sold across all orders -> "+totalProductsQuantity);
        System.out.println("");

        //9.Find the product whose total revenue is highest.
        Map<String, String> productIdNameMap = MockDataUtil.getMockProducts().stream()
                .collect(Collectors.toMap(Product::getProductId, Product::getProductName));
        String highestRevenueProduct = mockOrders.stream()
                .collect(Collectors.groupingBy(Order::getProductId, Collectors.summingDouble(Order::getOrderAmount)))
                .entrySet().stream()
                .max(Map.Entry.comparingByValue()).map(entry -> productIdNameMap.get(entry.getKey())).orElse("");
        System.out.println("9.Find the product whose total revenue is highest -> "+highestRevenueProduct);
        System.out.println("");


    }
}

